//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Complaint
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Complaint's destination is requierd.")]
        [RegularExpression(@"^[A-Za-z0-9]+[_\-' A-Za-z0-9]+$", ErrorMessage = "Please enter a valid description")]
        public string Description { get; set; }
        public int DeliveryManID { get; set; }
        public int SuperVisorID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
