//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DeliveryRequest
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        [Display(Name = "Shipment Description")]
        [Required(ErrorMessage = "Shipment's description is requierd.")]
        [RegularExpression(@"^[A-Za-z0-9]+[_\-' A-Za-z0-9]+$", ErrorMessage = "Please enter a valid description.")]
        public string ShipmentDescription { get; set; }

        //[RegularExpression(@"[0-9]*\.?[0-9]*?$", ErrorMessage = "Please enter a valid Weight.")]
        //[Required(ErrorMessage = "Weight is requierd.")]
        public decimal ShipmentWeight { get; set; }

        [Required(ErrorMessage = "Shipment's Source is requierd.")]
        public string Source { get; set; }

        [Required(ErrorMessage = "Shipment's Destination is requierd.")]
        public string Destination { get; set; }
        public Nullable<decimal> Cost { get; set; }
        [RegularExpression(@"[0-9]*\.?[0-9]*?$", ErrorMessage = "only Numbers are allowed.")]
        [Display(Name = "Recieving code")]
        //[Required(ErrorMessage = "RecievingCode is requierd,please contact with system admin.")]
        [MaxLength(50, ErrorMessage = "There is a problem with Recieving code please contact with system admin.")]
        public string RecievingCode { get; set; }
        public Nullable<int> ShipmentTypeID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> DeliveryManID { get; set; }
        [Display(Name = "Current Location")]
        public string CurrentLocation { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public Nullable<int> Rated { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual PaymentStatu PaymentStatu { get; set; }
        public virtual RequestStatu RequestStatu { get; set; }
        public virtual ShipmentType ShipmentType { get; set; }
    }
}
