//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Complaints = new HashSet<Complaint>();
            this.Complaints1 = new HashSet<Complaint>();
            this.DeliveryRequests = new HashSet<DeliveryRequest>();
            this.DeliveryRequests1 = new HashSet<DeliveryRequest>();
            this.Rates = new HashSet<Rate>();
        }
    
        public int ID { get; set; }

        [Display(Name = "Fisrtname")]
        [MaxLength(50, ErrorMessage = "First name length must be with a maximum length of 50.")]
        [Required(ErrorMessage = "First name is requierd.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Please enter a valid name.")]
        public string FirstName { get; set; }

        [Display(Name = "Lastname")]
        [MaxLength(50, ErrorMessage = "Last name length must be with a maximum length of 50.")]
        [Required(ErrorMessage = "Last name is requierd.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Please enter a valid name.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Email is requierd.")]
        [MaxLength(50, ErrorMessage = "Email length must be with a maximum length of 50.")]

        // [RegularExpression(@"^([0-9a-zA-Z]([-\\.\\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\\w]*[0-9a-zA-Z]\\.)+[a-zA-Z]{2,9})$", ErrorMessage = "Please enter a valid email.")]
        [RegularExpression(@"^([A-Za-z-_\.]+)([0-9])?@((\[[0-9]{1,3]\.)|(([\w-]+\.)+))([a-zA-Z{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter valid Email.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Phone is requierd.")]
        [MaxLength(50, ErrorMessage = "Phone number length must be with a maximum length of '50'.")]
        //ahmedsayed coment line(52) & added line(53) in 19/6 2:38 AM
        //[RegularExpression(@"^[0-9]+$", ErrorMessage = "Please enter a valid phone number.")]
        [RegularExpression(@"^(01)(0|1|2|5)[0-9]{8}$", ErrorMessage = "Please enter a valid phone number must be 11 numbers from Vodafone,Orange,Etisalat or We.")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Address is requierd.")]
        [RegularExpression(@"^[A-Za-z0-9]+[_\-' A-Za-z0-9]+$", ErrorMessage = "Please enter a valid address.")]
        public string Address { get; set; }
        public byte[] Photo { get; set; }

        [Display(Name = "Username")]
        [Required(ErrorMessage = "Username is requierd.")]
        [MaxLength(50, ErrorMessage = "Username length must be with a maximum length of '50'.")]
        [RegularExpression(@"^[a-zA-Z0-9_]+$", ErrorMessage = "Please enter a valid Username(ex: ahmed_50 ).")]
        public string UserName { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "Password is requierd.")]
       [MaxLength(50, ErrorMessage = "PassWord length must be with a maximum length of '50'.")]
       // [RegularExpression(@"^[a-zA-Z0-9_]+$", ErrorMessage = "Please enter a valid Password.")]
        public string PassWord { get; set; }
        [RegularExpression(@"^(?![0.]+$)\d+(\.\d{1,2})?$", ErrorMessage = "only Numbers are allowed.")]
        
        [Required(ErrorMessage = "Salary is requierd.")]
       
        public decimal Salary { get; set; }
        public int Authorized { get; set; }
        public int Active { get; set; }
        public Nullable<int> EmployeeType { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> HolidayID { get; set; }
        [Display(Name = "Current Location")]
        public string CurrentLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints1 { get; set; }
        public virtual Day Day { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryRequest> DeliveryRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryRequest> DeliveryRequests1 { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual Shift Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> Rates { get; set; }
    }
}
