//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.OfferImages = new HashSet<OfferImage>();
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }

        [Display(Name = "offer description")]
        [Required(ErrorMessage = "offer Description is requierd.")]
        
        [RegularExpression(@"^[A-Za-z0-9]+[_\-' A-Za-z0-9]+$", ErrorMessage = "Please enter a valid description.")]
        public string OfferDescription { get; set; }

        [Required(ErrorMessage = "StartDate is requierd.")]
        public System.DateTime StartDate { get; set; }

        [Required(ErrorMessage = "EndDate is requierd.")]
        public System.DateTime EndDate { get; set; }

        [RegularExpression(@"^(?![0.]+$)\d+(\.\d{1,2})?$", ErrorMessage = "Please enter a valid price.")]
        [Required(ErrorMessage = "Price is requierd.")]
        public decimal Price { get; set; }
        public int ShopID { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferImage> OfferImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
