//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferImage
    {
        public int ID { get; set; }
        public byte[] Image { get; set; }
        public int OfferID { get; set; }
    
        public virtual Offer Offer { get; set; }
    }
}
