//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int OfferId { get; set; }
        [Required(ErrorMessage = "Order's Quantity is Requierd.")]
        public int Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> Paid { get; set; }
        [Required(ErrorMessage = "Order's Destination is Requierd.")]
        public string Destination { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual PaymentStatu PaymentStatu { get; set; }
    }
}
