//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rate
    {
        public int ID { get; set; }
        public int EmpID { get; set; }

        //[RegularExpression(@"[0-9]*\.?[0-9]*?$", ErrorMessage = "Please enter a valid rate.")]
        //[Required(ErrorMessage = "Rate is requierd.")]
        public decimal EmpRate { get; set; }

        public int RequestsNumber { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
