//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ShipmentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShipmentType()
        {
            this.DeliveryRequests = new HashSet<DeliveryRequest>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage = "Shipment's name is requierd.")]
        [MaxLength(50, ErrorMessage = "Name's length must be with a maximum length of '50'.")]
        // Last Edit 6.29 am : (For Testing)
        [RegularExpression(@"^[A-Za-z0-9]+[_\-' A-Za-z0-9]+$", ErrorMessage = "Please enter a valid name.")]
        public string Type { get; set; }

        [RegularExpression(@"^(?![0.]+$)\d+(\.\d{1,2})?$", ErrorMessage = "Please enter a valid weight.")]
        [Required(ErrorMessage = "Shipment's weight is requierd.")]
        public decimal Weight { get; set; }

        [Required(ErrorMessage = "Shipment's PricePerKilo is requierd.")]
        [RegularExpression(@"^(?![0.]+$)\d+(\.\d{1,2})?$", ErrorMessage = "Please enter valid Price.")]
        //[RegularExpression(@"[0-9]*\.?[0-9]*?$", ErrorMessage = "Please enter a valid price.")]
        public decimal PricePerKilo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryRequest> DeliveryRequests { get; set; }
    }
}
